name: build

on:
  push:
    branches: [ "main", "dev", "actions" ]
  pull_request:
    branches: [ "main", "dev", "actions" ]

permissions:
  checks: write
  contents: read
  packages: read

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install clang clang-tidy clang-format g++ make valgrind gdb llvm libgtest-dev software-properties-common cmake curl libcurl4-openssl-dev pkg-config wget dos2unix python3-pip

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

